### ISSUE TITLE
useStoryblokBridge only works on the first instance it's called

### ISSUE THREAD

**Issue by readio** [storyblok/storyblok-nuxt-2#105]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Hi all

When using `useStoryblokBridge` to link story content to the Storyblok live preview/editor only the first time this is called is actually working. 

I have **header**/**page**/**footer** components, each with their own stories in storyblok with the content.

I am getting the stories for each component using `useStoryblokApi` inside `fetch`. This works great and I get all the content back from the API and can display this within each component.

In each each component I'm using `useStoryblokBridge` inside `onMounted` like below:

```
onMounted(async () => {
      if (story.value && story.value) {
        useStoryblokBridge(story.value.id, (evStory) => {
          console.log(evStory);
          story.value = evStory;
        });
      }
    });
```

The header component is rendered first and inside Storyblok the live editor works. My console.log test works and visually the data is updated live within the Storyblok preview.

The page and footer live editor does not work, and my console.log test does not get run at all.

If I remove `useStoryblokBridge` from the **header** component, the next one to load, **page**, works fine. **Footer** still fails. If I remove `useStoryblokBridge` from **header** and **page**, the **footer** works.

---

## Expected Behavior

Each instance of `useStoryblokBridge` should update the live editor within Storyblok

## Current Behavior

Only the first instance of `useStoryblokBridge` is linking to the Storyblok live editor

## Steps to Reproduce

Create more than one component with `useStoryblokBridge` and try updating the content within the Storyblok live editor/preview.

**Comment by SebbeJohansson** [comment]
Hi @readio! You should only start the bridge one time per page-load. This is something storyblok is looking at fixing (so that the bridge is only turned on once per page, no matter what you try to run).

Now! On to trying to fix your issue. How does your story look? Do you have the footer and the header within the page story some how?
The live editor doesn't support having multiple stories in the editor simultaneously. So you should only try to edit the page content you are editing. I hope that make sense! 😁
Easiest way to help would be if I could see the setup you have in storyblok and the code!

**Comment by readio** [comment]
Hi @SebbeJohansson I resolved this by creating stand-alone pages to display the individual Header/Footer elements.

**Comment by SebbeJohansson** [comment]
@readio Nice! glad to hear you managed to solve it!

**Comment by Dawntraoz** [comment]
Hi @readio, I'm so excited to tell you that we made a feature for this -> https://github.com/storyblok/storyblok-js/pull/254, finally multiple bridge instances will coexist! 🎉

You can now update this package to v2.0.0 with so many benefits like the removal of `axios `and the use of Fetch API finally, including the upgrade of `@storyblok/vue-2` with the JS SDK updated!

Let me know if you have any questions afterwards 🫂

**Comment by SebbeJohansson** [comment]
@Dawntraoz i actually have a question! Does this mean that we can go between stories now? Or what is the advantage between multiple bridges?

**Comment by readio** [comment]
Hi @Dawntraoz This sounds great. I will update and remove the workaround I had to put in place.
