### ISSUE TITLE
Text color gets applied as the background color for the RichText field when using renderRichText()

### ISSUE THREAD

**Issue by kubyshkin-vladyslav** [storyblok/storyblok-nuxt-2#139]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When I add a RichText field to a blok in my story, the "text color" setting is being applied as a `background-color` in CSS instead of `color`. Version 2.0.1

---

## Expected Behavior

The text color should be set as inline CSS

**What should be rendered as the html output:**

```
<p><span style="color:#AF1B1B">Hello World</span></p>
```

## Current Behavior

The background color is being set as inline CSS

**What is rendered as the html output:**

```
<p><span style="background-color:#AF1B1B">Hello World</span></p>
```

## Steps to Reproduce

1. Add a richText field to a blok in your story
2. Add the text "Hello World" to the richText field
2. Select that text and set the text color in the richText editor to red.
4. Follow the get started guide instructions to use the richText field => renderRichText()

**My vue file:**
```
<template>
  <div v-html="richtext"></div>
</template>

<script>
import { renderRichText } from "@storyblok/nuxt-2";

export default {
  props: {
    blok: {
      type: Object,
      required: true,
    },
  },
  computed: {
    richtext() {
      const doc = this.blok.richtext;
      return doc ? renderRichText(doc) : '';
    },
  },
}
</script>
```
5. Start your Nuxt app and see that the background-color is set instead of the text color

**Comment by sladkova** [comment]
the same for me, there's a similar issue reported in `storyblok-vue` repo: https://github.com/storyblok/storyblok-vue/issues/253

**Comment by alvarosabu** [comment]
Hi there @kubyshkin1994 and @sladkova  thanks for reporting the issue. Indeed several users reported this and it was fixed on https://github.com/storyblok/storyblok-js-client/pull/520 on the https://github.com/storyblok/storyblok-js-client repo.

We're currently waiting to update the versions on the SDKs to have this fixed as soon as possible. I will update this ticket when is done.

Thanks

**Comment by Dawntraoz** [comment]
This was merged in the JS SDK and this module long ago. In the case of other issues please report a new issue, thanks <3
