### ISSUE TITLE
Vue packages version mismatch (Nuxt 2)

### ISSUE THREAD

**Issue by michaelvcolianna** [storyblok/storyblok-nuxt-2#23]
**Please advise if I can provide any clarification or more details. I didn't see a bug template, but might have just missed it.**

**Noted issue**

Unable to run dev server/generate static files. Nuxt reports a fatal error of version mismatch:

`- vue@2.6.14`
`- vue-server-renderer@2.7.0`

This happens even on a fresh install, and in MacOS/Linux.

**Environments**

MacOS 12.3.1
Node 16 (16.15.x) via nvm

Rocky Linux 8.5
Node 16 (16.15.x) via nvm

**Steps taken**

- Created a new Nuxt 2 project (both `npx create-nuxt-app <project>` and `npm init nuxt-app <project-name>`
- Added Storyblok Nuxt 2 module with `npm install @storyblok/nuxt-2`
- Attempted `npm run dev` & `npm run generate`

**Result**

Error about Vue package mismatch.

**Expected result**

Development server runs and/or static files are generated.

**Notes**

Ran into this issue after installing & configuring the Storyblok Nuxt 2 module, but the error happens even if nothing is added to the Nuxt config file. Without installing the Storyblok Nuxt 2 module, dev/generate commands work.

**Result of `npm why vue`**

```vue@2.6.14
node_modules/vue
  vue@"^2.6.14" from the root project
  vue@"^2.6.12" from @nuxt/vue-app@2.15.8
  node_modules/@nuxt/vue-app
    @nuxt/vue-app@"2.15.8" from @nuxt/builder@2.15.8
    node_modules/@nuxt/builder
      @nuxt/builder@"2.15.8" from nuxt@2.15.8
      node_modules/nuxt
        nuxt@"^2.15.8" from the root project
    @nuxt/vue-app@"2.15.8" from nuxt@2.15.8
    node_modules/nuxt
      nuxt@"^2.15.8" from the root project
  vue@"^2.6.12" from @nuxt/vue-renderer@2.15.8
  node_modules/@nuxt/vue-renderer
    @nuxt/vue-renderer@"2.15.8" from @nuxt/server@2.15.8
    node_modules/@nuxt/server
      @nuxt/server@"2.15.8" from @nuxt/core@2.15.8
      node_modules/@nuxt/core
        @nuxt/core@"2.15.8" from nuxt@2.15.8
        node_modules/nuxt
          nuxt@"^2.15.8" from the root project
      @nuxt/server@"2.15.8" from nuxt@2.15.8
      node_modules/nuxt
        nuxt@"^2.15.8" from the root project
    @nuxt/vue-renderer@"2.15.8" from nuxt@2.15.8
    node_modules/nuxt
      nuxt@"^2.15.8" from the root project
  peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.0
  node_modules/@vue/composition-api
    @vue/composition-api@"^1.6.1" from @storyblok/vue-2@1.1.0
    node_modules/@storyblok/vue-2
      @storyblok/vue-2@"^1.0.3" from @storyblok/nuxt-2@1.0.2
      node_modules/@storyblok/nuxt-2
        @storyblok/nuxt-2@"^1.0.2" from the root project
  peer vue@"^2.0.0" from vuex@3.6.2
  node_modules/vuex
    vuex@"^3.6.2" from @nuxt/vue-app@2.15.8
    node_modules/@nuxt/vue-app
      @nuxt/vue-app@"2.15.8" from @nuxt/builder@2.15.8
      node_modules/@nuxt/builder
        @nuxt/builder@"2.15.8" from nuxt@2.15.8
        node_modules/nuxt
          nuxt@"^2.15.8" from the root project
      @nuxt/vue-app@"2.15.8" from nuxt@2.15.8
      node_modules/nuxt
        nuxt@"^2.15.8" from the root project```

**Comment by michaelvcolianna** [comment]
**Workaround located**

At the time of this issue/note, the result of `npm why vue` before installing the Storyblok module indicated Vue 2.7.0. Afterward, even if the module is removed, Vue remains at 2.6.14.

I added an override to the package.json file, specifying Vue 2.7.0, ran `npm update` and now the project starts the dev server/generates static files. Sample package.json data:

```
{
  "name": "my-app",
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "generate": "nuxt generate",
    "start": "nuxt start"
  },
  "dependencies": {
    "@storyblok/nuxt-2": "^1.0.2",
    "nuxt": "^2.15.8"
  },
  "overrides": {
    "vue": "2.7.0"
  }
}
```

I'm going to leave this open since I'm guessing something in the Storyblok Module is specifying Vue 2.4.16 and just needs to be updated, but feel free to close.

**Comment by oezkancodes** [comment]
I guess this package requires the Composition API. If you install `@nuxtjs/composition-api`  and add `'@nuxtjs/composition-api/module'` into your build modules, the issue will be gone. Maybe this should be made more clear in the README.

Edit 1: it seems like there is a new error now:

```bash
This dependency was not found:                                                                                                                                                                        
* @vue/composition-api in ./node_modules/@storyblok/nuxt-2/dist/storyblok-nuxt.mjs 
```

Edit 2: I solved this by adding the required version of the dependencies to my `package.json` :

```json
{
  "devDependencies": {
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14"
  }
}
```
