### ISSUE TITLE
 Support runtimeConfig

### ISSUE THREAD

**Issue by cjpearson** [storyblok/storyblok-nuxt-2#239]
### Description

Copied from https://github.com/storyblok/storyblok-nuxt/issues/32

> Right now the `accessToken` is compiled into the plugin. Would be great if storyblok would support [nuxt runtimeConfig](https://nuxtjs.org/guide/runtime-config). Example how @nuxtjs/axios implemented it: [nuxt-community/axios-module@351ea5e](https://github.com/nuxt-community/axios-module/commit/351ea5ee459eea53b9124de75ebfa7674d7ccd40)

### Suggested solution or improvement

> Example how @nuxtjs/axios implemented it: [nuxt-community/axios-module@351ea5e](https://github.com/nuxt-community/axios-module/commit/351ea5ee459eea53b9124de75ebfa7674d7ccd40)

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by Dawntraoz** [comment]
Thanks for the contribution you made, you're amazing 💜 Closing this ticket because it is already part of the repo!
