### ISSUE TITLE
401 error after following documentation for setup with V2 spaces

### ISSUE THREAD

**Issue by drewclem** [storyblok/storyblok-nuxt-2#63]
I've been attempting to spin up a new Storyblok site using Nuxt 2 and a fresh Storyblok V2 space but immediately run into 401 errors _only_ with native V2 spaces. The code works as expected when swapping the access token to a V1 space.

I've tried Node versions `14.18.1`, `16.9.0`, and `15.0.0`.

[Here](https://github.com/drewclem/storyblok-example) is a repo that replicates the issue.

Again, this 401s if you use a space created after V2 launch and works as expected with a V1 space.

**Comment by Dawntraoz** [comment]
Hi @drewclem, is your space in the v2 US spaces? Because, for that, you will need to add the region parameter in the module options ([See the Options part of the readme for reference](https://github.com/storyblok/storyblok-nuxt-2#options))

**Comment by drewclem** [comment]
It is! My apologies, I meant to close this issue weeks ago.

**Comment by Dawntraoz** [comment]
Oh no, don't worry. Apologies from our side for the delay, we have been so busy with the conference season 🤗
