### ISSUE TITLE
No typescript support 

### ISSUE THREAD

**Issue by juan-kreuzfahrtberater** [storyblok/storyblok-nuxt-2#69]
We develop a nuxt2/typescript project . Isn't there a @types/@storyblok-nuxt-2 or what would you recommend ? . creating out d.ts file?

**Comment by alvarosabu** [comment]
Hi @juan-kreuzfahrtberater unfortunately no, although most of the types come from the core packages https://github.com/storyblok/storyblok-js-client maybe you can use some of them.

If not, create a d.ts file would be the way to go
