### ISSUE TITLE
Resolved relations do not replace UUIDs anymore in 1.2.0 and above

### ISSUE THREAD

**Issue by bbm-marcostam** [storyblok/storyblok-nuxt-2#84]
Hello,

We have been using version `1.1.0` without any issues for a while. However, after upgrading to `1.2.0` (or above), when fetching stories using `useStoryblokApi()` during local development, the resolved relations have stopped replacing the UUIDs (they are present in `rels`). Our query looks something like this:

```javascript
async asyncData() {
  const story = await useStoryblokApi().get(
    'cdn/stories/uk/example',
    { resolve_relations: BlokName.field_name }
  )
  return { story }
}
```

and we have a content relationship field called `story` which gets returned as

```
story: '22581164-1b3c-4b39-8a14-9d30ed0edb9b'
```

Downgrading back to `1.1.0` and running the exact same query replaces the UUID with an object consisting of the resolved relation as expected.

**Comment by Fabioni** [comment]
Hey, I am facing a similar issue: The resolving in asyncData works on client-side but not on server-side. Still, it is present in `rels`.

My workaround is to use `new StoryblokClient({accessToken})` instead of `context.app.$storyapi` or `useStoryblokApi()`:
```js
import StoryblokClient from "storyblok-js-client";
...
async asyncData() {
  const Storyblok = new StoryblokClient({
    accessToken: process.env.STORYBLOK_TOKEN,
  });
  const story = await Storyblok.get(
    'cdn/stories/uk/example',
    { resolve_relations: BlokName.field_name }
  )
  return { story }
}
```

**Comment by kubyshkin-vladyslav** [comment]
+1

**Comment by Dawntraoz** [comment]
Hi @bbm-marcostam @Fabioni @kubyshkin1994 👋 You can update to the latest version of the package finally!

Sorry it took us so long to respond, it was an isolated bug related to the serialization made in the SSR of Nuxt 2, so it wasn't affecting other SDKs and for that, we needed to properly test each use case to find the missing piece after the JS SDK got rid of `axios`.

Now, please feel free to test everything with the new version again and report any other issue you encounter in the future 💜 We are improving the time allocation for maintaining the SDKs, so expect updates more often!
